%% Lecture 3, DSGE course
% This version: updated on May 7, 2019.

clear
close all
clc

%% Parameters
alpha    = 0.35;  % capital share
beta     = 0.95;  % discount factor
delta    = 0.1;   % depreciation rate
rho      = 0.95;  % TFP persistence
sigma    = 3.00;  % CRRA
sigmaeps = 0.01;  % TFP standard deviation


%% Deterministic steady-state

z_ss = 1;
k_ss = (alpha*z_ss/(1/beta-1+delta))^(1/(1-alpha));
c_ss = z_ss*k_ss^alpha - delta*k_ss;
y_ss = z_ss*k_ss^alpha;

ss_matlab = [c_ss,k_ss,y_ss,z_ss]';

save paramfile.mat z_ss k_ss c_ss y_ss

%dynare stochastic_growth_dynare.mod noclearall
dynare stoch_growth2.mod noclearall

%% Steady states computed by Dynare

fprintf('\n')
disp('------------ END DYNARE ----------------------------------------')
fprintf('\n')

disp('Steady-state values computed in Matlab:')
disp(ss_matlab)

disp('Steady-state values computed by Dynare:')
disp(exp((oo_.steady_state)))

% Since we specified the model in logs, the steady state that we get from
% dynare are in logs too

%% Plot IRF generated by Dynare

k_e_new = [0; k_e(1:end-1)];

figure(2)
subplot(2,2,1)
plot(z_e,'linewidth',2)
title('TFP')
yline(0,'r')

subplot(2,2,2)
plot(c_e,'linewidth',2)
title('Consumption')
yline(0,'r')

subplot(2,2,3)
plot(k_e_new,'linewidth',2)
title('Capital')
yline(0,'r')

subplot(2,2,4)
plot(y_e,'linewidth',2)
title('Output')
yline(0,'r')







